sudo: required
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - RELEASE_NAME="aat"
  - DJANGO_APP="cohort_manager"
  - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
  - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
  - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master
  - secure: "RYsYPPjOtNP73lTBnzmNy2OZggc4xXkVNaXK17buudtBRI+YyaUMIntLhJYgUxOWvu4hGVmVuPyTwZL6NjSXQA+4csDfwuizkLB7beQ/PhkwM0tyiMv4NOVDhq9B5YUbUQNZv2CkDyWTsvIVyiBC+a/lR3e8tTzvT2pZRp1nG9+V8QDANupPR0K8Kzc11+Yl7cRnl8v9lBRVeX+IuSvn3l0wuUaXaZj32FjmO8b42pdzuYxwNbNar6j075bpuU1jxyqOIAkvNfsLO7HwJJdDPZuJ/ZNYr/sQeRNyBCB92FXcPblR5C6FZN/ikqddKGHCoZW150/rXAqt6fgB8bVcVsqIYyP8ZJjSpmRh7kRAS9cDNDiEyDYyMbUydyS6NBpkgwSViTg5fYlVjkwbwshibXmuV6UyVBumDEga5XDQS/ZsD24VXSji9rkkIzzgEbs+fm05uPzVPKszmfnV3h2zrOW5gb58WZ2eB9fAN1ePYbYeoDBJyStf73Zc+izgsxqcPFh3+PMdE3tfl0/nR0qUJpAMqnfWyktnoKkFrwI+JdClwsQWLHVpBXlReBf2rAmhIOQLgfjJ4fVdEYMPs77xkpX7ES9tcPGBEfsqR8C5svjmi9keVMRsM4qMx+13TnNWhjQRfj1MYt18MzkHwPNOzFOA+VD7sa4VMBwCvu2nMUE=" 
  - secure: "FAgPazZm31QIGjATjTxzt3tW1yMKRznplQYu7PzBxXaiIknaOd0HrblTIMun1JyTsFjukux0F24qWu8i/gS9LcIUayE3vS0ZUJy6Gz898w7NVMaNAnSL5WFQPJ0CJPij1cZS3gIH60MeBIPNo0HNMWIeACsiY41HlmhfWnrkAP1syG3Uo+s01vjheP1ZPuaC6qq+zAffQYlgJGW3vFJGyYGEgDp8uYtlfnOXyP167402783EAoJkf0k9GCUUtks927WPjUMxJh3OuARfC3dLwjh4/NGfBmQGagfhKq6s8WqJuOfahATZ0HJdU4RPBUC6/eCh6NQ8beQlKrTWmrekEEfy+4VfMzLWG010B3vbHqcbjeDvrtxs81FluuKQpIVhOuQkVPRZsSnbWWpUUk6L5epXPNy3Pg4JZgvaPmEEYRcshpJpHjzd5GrOav+vnqfiDG0cwRcwSzSJ5dqH8dNDNYw5/+ILQp7LpxlECMabKuj3iUlZTxZXoxHEMYENYZjX408AiYMd07CgnRjoRo3n2ZLYJlzIJWm5kgq/Gcv56RZbnNXNgQqwyJngt7eL7kuj6YB9v4umiv4BiWOHAfsO72IEnDX1NnVuRYjW9RBONVV9AvWxTpXs6vnEo2BFxa5QxwBbZjC97+cul/5kPEERXTbDwznFuxurwJpIa0vImzo="
  - secure: "dNkVjzbaRuYZ8JRFtVl8gkx6mIjhbJ8roibq2XtTMzWBQWxIzAgU8zUOjsPFJO0a6xjG480JGqxUQNcUvoye+8Hf48EOUpED8FBHAL2vpHvd2D0S4vvrLZhw7kIPf1YLErUZIjJcy6FFrHeC/5YvOjLAFnrxSLt2NLoiDKkxeQfxMd3bT3WzM4jWfiH9IPWoKbRGpU7GOUMAgbBtwexIF6IPEWsjWu5XV4Tt5OvtzsKA888XwAxOsZiDyfEMtTkVN7WsJQERPm+cwT95YFZUsimIIHo0hFsXKf1X0+D1ldQ08+yz0dyEJKrn73pX+LMsmlFtsZLvUFGScau85qxQBomM5avTwCy+2Ht2XHtcmlcVzQAOEjscY6sfZmQKZlp2b8VscA+0neI4/x9RbIZxIZkdyFDZbx3kTjPhkT2BIett66VB3r1mSoBPDqMyQMFrERuJZHX+zwZY1KecFW99NVgmTlnrm3vezJsXKS+9Q225MvGc5al7E3r5t/SprNAEV4S7rzbwIZKmTYmAYo9oxj8bNQGQyhEBDAhy/5v3zzajOblquypU/nmuN98PIoqWU0ZS2+SdVKVRChQUqpPpJAoRShhXcglcm8y7pNLRv5tHnGRJYnnX7WDhH7FYYHVBju67ArEfwmLd+ttQqZo6XGMnG1TfXAxSziop0DApADc="
install:
- docker build -t "$IMAGE_TAG" .
before_script:
- pip install coverage
- pip install coveralls
script:
- docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev"
  -e "AUTH=SAML_MOCK" "$IMAGE_TAG" bash -c ". ./travis-ci/test.sh"
after_script:
- cp /tmp/.coverage.* .
- coverage combine
- coveralls
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" =~ ^(develop|master)$
  ]]; then curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash; fi
cache:
  directories:
  - "$HOME/helm"
  - "$HOME/kubeval"
