sudo: required
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - RELEASE_NAME="aat"
  - DJANGO_APP="cohort_manager"
  - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
  - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
  - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master
  - secure: mx96Y1wLH79iFbGJcrmZhN97Sf9lnpAxSvAoa/8zUSDkLDAE3cUF3/UTqviR18yWXHHme4aBl5iV7C5JdF4QT+BLRxAvk2DxE+SVv23IXSC8MWwH00cPtivTvKuDiWUru2lpAvF/h0zu0NR9iHZKZNJO0zAP7qhUDoYRRTgBxjrSpGcYuRQ2mbb6esl31NkJeOmpXz4g7Tt2Vu1FwYrdIyG3qFEGT5bJfYc/0dJf2Rud6ZD4YZmQ967tIqTnjE2/ht0K/T9d0fSi54LXL4sEirVv2Ua/5OcJO8gxO490QK7wzA+XhKKjqU3vRse8U9+dXeFkJA6aRnvneMsMBkkK9BdiJhWfPxYXnjKkr/rkL9vpZkbGDx8n4qa5ASFmCgXBJ49f56dn7kOWZ+YsOSUS9/N7bzpZitBaE2qPSI6xAkrUjbu4+Cy3V5UYz+yBFW4NxaofhDbnOLgF6pcEVeAKDtHWsuEDGMuaEw2Rw1S+ZV77UCebPnnGeEOIm+2oUvgmxX/z7/ZDvUHrCdQBcpURkQ7nzSU66LaNHt9pm7CqjbXGrARHx7R9NCrxNnKq4RHYi5eTNuMnpE7RVASDy6G/+VKmreHnCM4Mc6FunEdWJWQJrVuCagNm9HRXc+Q6nmCvuRue1Wm71Z0Fiz4no2uy2TMJ7niWsD6IPbpIoWUYhtc=
  - secure: Tx0Ae48o8nNkXd8ZocDVT4OmUX8NqNtHpAgSBt2eo7AnxxULCBWyt57fynsAcxvq2PebEFl0eUmgoZnE2MHm8OHLOyYkAgP4hluSzvSySfRkDN0rf4iJgMOAdkyzUP4F17nGDJpdDefQLoBWD87ovchAUcWDc4K2RyNyrwJJOiodetPCWxYlkA2bYF3m9v54IwTmOi/4mS8F5yiwYCgz+ujbtZjaDdal1HhXSRRxbulZ2I40pu4tVeuIsIGGB0FIgZCx/ATSC6TuDAmfTno3cIXDci61tq6ATB38ilkp/MpBUdzQmfFXGOOjDZK++w5uvnnp5DXz7azJeocILodyAddO8KPXJTinG74raCRkTAfr5KxnBHrj7Iuh2oWETdziwM0aHrehytP0V8KKKUZFEjGSvfG3PuDsrTQeYY63TKdLDy+MjgbblW+L0uubutn1ZQwjLFFE+MzjVngdoPgAL9WpcODnIZjRqXuTRGT7hwL7Ij2wFm5NdCpFaPc37oURhfo4ry6npVZy/gEKbJ1++bCPxE9qbG9rB8qbKlGVSNu81wnmxIci5NXpnhhTIBUGnJPfRoOUbpVpJ45nMERSMaQZUkhYaSI/SEEru/DSeLZp7bC9Nu4HTm9/8C15KzC5E9FDCSMl2i0hvJEQtSokfpUE0A6caHJfZ2oOf31RFDc=
  - secure: loi/V0tM4N0vKBuC/wEVnLi4ypK11AsaPObwO5nfJEfRHoyKS5NwdiPAP3zW91QdRaZGa2WS9xfWjx6N94b3a+YD7ZKD0U002qMbw/BbARMUaXa3es/Q4IxNGYOYGV4PTRyb2vMxvMK8BGUIr0uoixlQE/WsUG3DLskwUko55HaTSWfxbILZl7hwA/GsyoYQ3O0hMIKFM2GETMUV772PznG8DQgfivnmGRgBhr8THjGgHTlJnAj9ok2SBFPhK1ERuNVWcRU8zoR1pHcHtKJPUW6PAvCIt+KjrMfZRKmvk5dvCrsthE+Y4XNDtZkVeWjz4JgciIXHu8MAdogtDdR6LRwTBeJGG2dhTyYuv8aHJMs+47NVhDG7Q4/TqunAeqi/qVhBotr7ntpkx+hwh/oLz4CMwWY9uZE9IDUMD3qFx270J0M8Qp/LhVK2/bV9guoeE3KPESbbG/A1/DG5cicJsSLNYA4CZwmsET0/9ZM7269w08nYgOMuPUUy9aSTHsQ3wZ/rQO0EQsfO1O1g4IGkaM/FMqf/jqvIyCQuxqQcUdMI1jDjZXDYmWFhgwMZFQEYJhk3Sgf3eoDWf8FMpu/KS7O8vb69d+EkREglaBKgHEeyZ4JJE37e5QCIFWV0+2fms05d6TUum4ANyFmsawJk2VsbxzsSUlR6Ys8qUHdO+uQ=
install:
- docker build -t "$IMAGE_TAG" .
before_script:
- pip install coverage
- pip install coveralls
script:
- docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev"
  -e "AUTH=SAML_MOCK" "$IMAGE_TAG" bash -c ". ./travis-ci/test.sh"
after_script:
- cp /tmp/.coverage.* .
- coverage combine
- coveralls
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" =~ ^(develop|master)$
  ]]; then curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash; fi
cache:
  directories:
  - "$HOME/helm"
  - "$HOME/kubeval"
