sudo: required
dist: focal

language: python
python:
  - '3.6'

services:
  - docker

env:
  global:
    - RELEASE_NAME="aat"
    - DJANGO_APP="cohort_manager"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
    - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master
    - secure: "TrDHqi4ZK5iF53RuoEyPRQMiSxq86rvLl8DibUo87SJW5k/2eL0E1R+H6bIh2XMdbHaW3xWPOMICyvPfYiBrBqmdC1BRNN9UikqNcsN/3Bw4aeFJ+wyhvszfZ/t83b0Gd5KgmJatKyzzvOHnyglnURr5inJEndlTKEy0XKkE64jWJ593qqV5hkgOSL94am3RFAUeCc55Tz0DWn/ovXw43e6HNBSagHE52eYNH1fSey1djNlEs7D35ivh4nuwVHMmukwM3lxTFe4BEka2Lg2hJcmzy3MB/XDZGw8dvKtR11n5c9lIsNVewH5X0OqkdzWA4/CFr35TQ73JuhlfwMZWZXuRMX0vXHVil1VOfon9j4s+GACFrRIHRgnLEkvnxPK3dStpe+wGNZCUeXyUFbVL4yWwNS5gYRxFkZ11FHar1ZpkFBst3rUs7EWd5SOfMziePzAbKNpmEYjtyqGasoIERxR7nfNlmS/m8d/3nZZ/60bRrlNk67Imn0KS/aIC3qdDXdb/6bv3nf/Ye5a6vKXfaOnUby2stp9nTCYfoHy5mjduB6v3qpQv7LttRxsWK7C4LIgPA19hOaexUAYbAMJ9UVtFEOTZU+mzD92zlQrcW9vYG8wzSyr67Ucmq8VXH53q6wHCTtCxQl0lR0gneO7nHBunWJL4o5SvIb4O7q9YG98="
    - secure: "a+gDI6KCU+jwmQu7LnJX5b1wBnqXrtdKKrpoHB5QNTV+WkZbSJA/rD2Y0jePu/VtdOLJ4B1/GrqHkYM2yOVtGdbU8aQAywTSdvBHHbQU7IK8eqY6uUFpj1PzdUZz6wxGfy4106wJ+PV2In/68SZCL4Eb1+JdyUvH4cY6/x+1fYk9RlMcTc5HoqtNOHeeK6OIGYYhrFKte93Am62A5Z97a83VZgqdLomJ4ElCqBs/M22OVEGcFqSIIJWYf37l2Rhcq+VX1Q+105tP7ughHE6afuNUw29rphMG6ItGk0Q/gn0rpy5janGFiFy5JFw01+tgh1u9kVdnx1enVeNsWdABYivbEbePDTXyfSMShF584D7l+2DCDr7RkhGpSCu7g1GMBaMoPdthbOi3TtRRoCPnp41Nt1H4W9nFoC7sdFehlJWxIhOH/mKE1DXycjTaIfnAHQHfLfV/1tV1zODoOFPwTBBvLmApIPeugSfWPuBZueyqVgz3W3QFxskbAl6endybeKre/zXvUD3JYih3zT5IbpvAL3j6l5y4Y0EqSnrvrwE+/ytlqTkDxCAu/L4VrzYxmuHy1Pz3vgQedZGXEClbHrazGJdphdcBt49ZNuR5ULSvsxSLzsMmfnl/v5YSnkoO/yQmJjOqR7fhH2wW5AbloJwVDv86r1cMrbRigevFZmc="
    - secure: "JnVHnh7SfSnEaCVTTQ8R5objTNHsxtjQbLEAsCFWQDb+5D9AHTDnOk9MwTre8mvz6mmOz9pR44W+CN8UkHMXG4ifl8ZzNMtI7aloFsdrMXFAu7+c/cwXNuQp10g2Wwq8S5k8dWEqR1foTc+pRMmsDpbOvx3b/5U7dBKA2BVV6HOptc5o5VI/9MViSoZF8THBdOOvwqgUb+b1n1IyKmflo7LrHCOjs8YQiqaggakmcqAY+t6s7E7D+20worOCjMYW47nYBbB7hhwbJ0faqNG6+nPgBFsjSLgbAMYg0slfNaIWZxVaO5duKSiG8cWkCpcv74oMNRB6LtYiO+XGFeBwgWXmBLr67B1MsE6Pwdqn79xxqrtz8dZr03+ziTKCE13fdOF3f+mc6H/lA45i7/fwTb/wvHy5YmQruLLXaiJZmfDqmubJg6XVFImtkdUugfqck4EyBN4y2S3eZkLpuSsT7lIOMVmnJ1CAu7GbhK5wo95vv2y3iqrBt3BaZ2jn9gUJLt3LL3ypl1QzgXnhXdkRKUP/wwf7HgvhLXyNytenZuiQGK2SwLMRBhYrx5sRdKsBTbKx7MljKYO+Muq2mscbmTRu8D61ILtvDuesUwSKtmGm4Y1l7ddt4jdRKSdw1MkUSpCsqm66RR23mVLP/V+gXCT4mqMIQtgcoPV68XO2l9A="

before_install:
  - nvm install 14.15

install:
  - docker build -t "$IMAGE_TAG" .

before_script:
  - pip install coverage
  - pip install coveralls

script:
  - docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev" -e "AUTH=SAML_MOCK" "$IMAGE_TAG" bash -c ". ./travis-ci/test.sh"

after_script:
  - cp /tmp/.coverage.* .
  - coverage combine
  - coveralls
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" =~ ^(develop|master)$ ]]; then
    curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash;
    fi

cache:
  directories:
    - "$HOME/helm"
    - "$HOME/kubeval"
