version: '3.4'

services:
  app:
    environment:
      - AUTH=SAML_MOCK
    restart: always
    container_name: app
    build:
      context: .
      target: app-container
    volumes:
      - ./cohort_manager:/app/cohort_manager
    ports:
      - "8000:8000"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.16.0-jessie
    volumes:
      - ./package.json:/devtools/cohort-manager/package.json
      - ./webpack.config.js:/devtools/cohort-manager/webpack.config.js
      - ./cohort_manager:/devtools/cohort-manager/cohort_manager
    working_dir: /devtools/cohort-manager
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
