# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.4 on 2019-12-24 00:25

import cohort_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0002_auto_20191218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentimport',
            name='cohort',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[cohort_manager.models.validate_cohort]),
        ),
        migrations.AlterField(
            model_name='assignmentimport',
            name='major',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[cohort_manager.models.validate_major]),
        ),
    ]
