# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.4 on 2020-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0003_auto_20191224_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='campus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Seattle'), (2, 'Tacoma'), (3, 'Bothell')], default=1),
        ),
    ]
