# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.4 on 2020-01-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0004_assignment_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sdb_app_status',
            field=models.IntegerField(null=True),
        ),
    ]
