# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.4 on 2020-01-24 22:52

import cohort_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0005_assignment_sdb_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentimport',
            name='major',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
