# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.11 on 2020-10-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0006_auto_20200124_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleGoldAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_selection_id', models.CharField(max_length=30)),
                ('purple_gold_new', models.IntegerField(null=True)),
                ('assignment_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cohort_manager.AssignmentImport')),
            ],
        ),
    ]
