# Generated by Django 2.2.11 on 2020-10-22 01:34

import cohort_manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0006_auto_20200124_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleGoldAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.CharField(max_length=30, validators=[cohort_manager.models.validate_system_key])),
                ('application_number', models.PositiveIntegerField(validators=[cohort_manager.models.validate_application_number])),
                ('admission_selection_id', models.CharField(max_length=30)),
                ('assigned_cohort', models.IntegerField(null=True)),
                ('assigned_major', models.CharField(max_length=30, null=True)),
                ('campus', models.PositiveSmallIntegerField(choices=[(1, 'Seattle'), (2, 'Tacoma'), (3, 'Bothell')], default=1)),
                ('sdb_app_status', models.IntegerField(null=True)),
                ('purple_gold_assigned', models.IntegerField(null=True)),
                ('purple_gold_new', models.IntegerField(null=True)),
                ('is_international', models.BooleanField(null=True)),
                ('is_wa', models.BooleanField(null=True)),
                ('assignment_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cohort_manager.AssignmentImport')),
            ],
        ),
    ]
