# Generated by Django 2.2.17 on 2021-01-19 20:51

import cohort_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0007_purplegoldassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyskeyImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_override', models.NullBooleanField(default=False)),
                ('upload_filename', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.SmallIntegerField(null=True)),
                ('imported_message', models.TextField(null=True)),
                ('quarter', models.IntegerField()),
                ('campus', models.CharField(max_length=30)),
                ('cohort', models.CharField(blank=True, max_length=30, null=True, validators=[cohort_manager.models.validate_cohort])),
                ('major', models.CharField(blank=True, max_length=128, null=True, validators=[cohort_manager.models.validate_major])),
                ('is_purplegold', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_reassign', models.BooleanField(default=False)),
                ('is_reassign_protected', models.BooleanField(default=False)),
            ],
        ),
    ]
