# Generated by Django 2.2.17 on 2021-01-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0009_syskeyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syskeyassignment',
            name='admission_selection_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='syskeyassignment',
            name='system_key',
            field=models.PositiveIntegerField(),
        ),
    ]
