# Generated by Django 2.2.17 on 2021-04-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0011_auto_20210209_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleGoldImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('campus', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('imported_date', models.DateTimeField(null=True)),
                ('imported_status', models.SmallIntegerField(null=True)),
                ('imported_message', models.TextField(null=True)),
                ('quarter', models.IntegerField()),
                ('upload_filename', models.CharField(max_length=100, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurpleGoldListAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_selection_id', models.CharField(max_length=30)),
                ('purple_gold_new', models.FloatField(null=True)),
                ('pg_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cohort_manager.PurpleGoldImport')),
            ],
        ),
        migrations.RemoveField(
            model_name='syskeyimport',
            name='is_purplegold',
        ),
        migrations.DeleteModel(
            name='PurpleGoldAssignment',
        ),
    ]
