# Generated by Django 2.2.17 on 2021-04-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0012_auto_20210408_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syskeyimport',
            name='cohort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
