# Generated by Django 2.2.17 on 2021-06-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0013_auto_20210416_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='syskeyimport',
            name='decision',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
