# Generated by Django 2.2.17 on 2021-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort_manager', '0014_syskeyimport_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syskeyimport',
            name='decision',
        ),
        migrations.AddField(
            model_name='syskeyassignment',
            name='decision_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='syskeyimport',
            name='decision_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
