ingress:
  enabled: true
  tls:
    aat:
      secretName: aat.axdd.s.uw.edu
      hosts:
        - aat.axdd.s.uw.edu
  hosts:
    aat:
      host: aat.axdd.s.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
database:
  engine: postgres
  secretName: aat.axdd.s.uw.edu-sql-secrets
  hostname: aat-db-service
  name: aat-db-prod
externalService:
  enabled: true
  name: aat-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.24
  servicePort: 5432
repo: admissions-cohort-manager
instance: prod
branch: master
certs:
  mounted: true
  certPath: /certs/aat.axdd.s.uw.edu-uwca.cert
  keyPath: /certs/aat.axdd.s.uw.edu-uwca.key
  secretName: aat.axdd.s.uw.edu-uwca-certs
image:
  repository: registry.hub.docker.com/acait/aat
  tag: IMAGE_TAG
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true

environmentVariables:
  - name: ENV
    value: prod
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://aat.axdd.s.uw.edu/saml
  - name: CLUSTER_CNAME
    value: aat.axdd.s.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: aat.axdd.s.uw.edu-secrets
      externalKey: axdd/kv/data/aat/prod/secrets
      data:
        - name: django_secret
          property: django_secret
        - name: bulk_api_key
          property: bulk_api_key
    - name: aat.axdd.s.uw.edu-sql-secrets
      externalKey: axdd/kv/data/aat/prod/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: aat.axdd.s.uw.edu-uwca-certs
      externalKey: axdd/kv/data/aat/prod/uwca-certs
      data:
        - name: aat.axdd.s.uw.edu-uwca.cert
          property: aat.axdd.s.uw.edu-uwca.cert
        - name: aat.axdd.s.uw.edu-uwca.key
          property: aat.axdd.s.uw.edu-uwca.key
    - name: aat.axdd.s.uw.edu-ic-certs
      externalKey: axdd/kv/data/aat/prod/ic-certs
      data:
        - name: aat.axdd.s.uw.edu-ic.cert
          property: aat.axdd.s.uw.edu-ic.cert
    - name: aat.axdd.s.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: aat.axdd.s.uw.edu-secrets
    secretKey: django_secret
  bulkAPIKey:
    name: API_TOKEN
    secretName: aat.axdd.s.uw.edu-secrets
    secretKey: bulk_api_key

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
